dirty component
Crusader727/FindMyPet pull request #1
Opened 2019-09-07 13:19 UTC by youraavdeev

2019-09-08 16:13 UTC, Crusader727 requested changes
В целом хорошо

2019-09-08 16:13 UTC, Crusader727 commented on src/components/publication-preview/publication-preview.scss
> +    font-family: Roboto;
надо вынести в общий файлик

2019-09-08 16:13 UTC, Crusader727 commented on src/components/publication-preview/publication-preview.scss
> +        color: black;
цвета тоже выносим в общий файлик

2019-09-08 16:13 UTC, Crusader727 commented on src/components/publication-preview/publication-preview.scss
> +                font-size: 13px;
фонтсайзы тоже

2019-09-08 16:13 UTC, Crusader727 commented on src/components/publication-preview/publication-preview.scss
> +            &___PrefixName {
нейминг не по флоу - надо prefix-name

2019-09-08 16:13 UTC, Crusader727 commented on src/components/publication-preview/publication-preview.tsx
> +    static defaultProps = {
дефолт пропс не делаем

2019-09-08 16:13 UTC, Crusader727 commented on src/components/publication-preview/publication-preview.tsx
> +    props: PublicationPreviewProps;
это не надо делать

2019-09-08 16:13 UTC, Crusader727 commented on src/components/publication-preview/publication-preview.tsx
> +        const { name, tags, descriptionElement, address, subways } = this.props;
не соответствую поля пропсу в интерфейсе у тебя нет этих полей, там у тебя только publicationPreview

2019-09-08 16:13 UTC, Crusader727 commented on src/components/publication-preview/publication-preview.tsx
> +                        <div className={s.publicationHeaderNamePrefixName}>
надо учесть что "его могли бы звать" может и не быть, т е у животного есть имя

2019-09-08 16:13 UTC, Crusader727 commented on src/components/publication-preview/publication-preview.tsx
> +                        {subways.map((subway) =>
нужно учесть что станция может и не прийти(ее нет)

2019-09-08 16:13 UTC, Crusader727 commented on src/components/publication-preview/publication-preview.tsx
> +        const { name, tags, descriptionElement, address, subways } = this.props;
это очень важно, линтер не может не ругаться здесь

2019-09-08 16:13 UTC, Crusader727 commented on src/types/publication-preview.d.ts
> +    address?: string;
адрес неправильный тип

2019-09-08 16:13 UTC, Crusader727 commented on src/types/publication-preview.d.ts
> +    subways?: Array<{ subway: string, color: string }>;
subway будет в поле адрес
и на будующее не пишем subways?: Array<{ subway: string, color: string }>;
на примере этого
subways: Subway[];
и в другом месте обявлен тип Subway
interface Subway {
   name: string:
  color: string;
}

2019-09-08 16:13 UTC, Crusader727 commented on src/components/publication-preview/publication-preview.tsx
> +                <div className={s.publicationImage} style={{ backgroundImage: `url(http://newrussianmarkets.com/wp-content/uploads/2018/10/f2d0f2696e6151d756c59f26a4bf6307.jpg)` }} />
убери хардкод

2019-09-08 16:14 UTC, Crusader727 commented on src/components/publication-preview/publication-preview.tsx
> +                <div className={s.publicationImage} style={{ backgroundImage: `url(http://newrussianmarkets.com/wp-content/uploads/2018/10/f2d0f2696e6151d756c59f26a4bf6307.jpg)` }} />
я про ссылку

2019-09-08 19:32 UTC, youraavdeev commented on src/components/publication-preview/publication-preview.scss
> +            &___PrefixName {
только в этом месте нейминг не совпадает с флоу? или везде через тире хуярить?

2019-09-08 19:33 UTC, youraavdeev commented on src/components/publication-preview/publication-preview.tsx
> +    static defaultProps = {
почему?

2019-09-08 19:35 UTC, youraavdeev commented on src/components/publication-preview/publication-preview.scss
> +    font-family: Roboto;
куда и как?

2019-09-08 19:35 UTC, youraavdeev commented on src/components/publication-preview/publication-preview.scss
> +        color: black;
куда и как?

2019-09-21 17:41 UTC, Crusader727 requested changes

2019-09-21 17:41 UTC, Crusader727 commented on package.json
> +    "react-multi-carousel": "^2.2.5",
где тайпинги?

2019-09-21 17:41 UTC, Crusader727 commented on src/components/ui/publication-preview/publication-preview.scss
> +        width: 290px;
почему тут ширина? оно должно само расчитываться

2019-09-21 17:41 UTC, Crusader727 commented on src/components/ui/publication-preview/publication-preview.stories.tsx
> +const name = "Шарик";
не очень, надо в объект, а не каждое поле с новой строки, тогда можно будет и деструктуризацию заюзать

2019-09-21 17:41 UTC, Crusader727 commented on src/components/ui/publication-preview/publication-preview.tsx
> +                            {isEmpty(name) ?
```
condition
   ? elem
   : elseElem
```

2019-09-21 17:41 UTC, Crusader727 commented on src/constants/publication-preview.ts
> +export const NAMES_ARRAY: Array<String> = ['Шарик', 'Дес', 'Тузик'];
не должно быть хардкода имен, он с сервака приходит

2019-09-21 17:41 UTC, Crusader727 commented on src/types/publication-preview.d.ts
> +        subways?: Array<{ subway: string, color: string }>
так и не пофиксил

2019-09-21 17:41 UTC, Crusader727 commented on src/utils/randomName.ts
> +export const randomName = (arrNames: Array<String>) => {
randomName не нужен оно с сервака приходит

2019-09-21 17:42 UTC, Crusader727 commented
еще не верю, что у тебя линтер не ругается

2022-03-21 22:09 UTC, merged